### PR TITLE
update de-translation

### PR DESCRIPTION
**Pull request by cloud2018**
The translation does not take into account whether the layout represents the text in its entirety.

### CODE REVIEW

**Comment by rubo77** [comment]
What do you mean? Which layout? which text?

Feel free to merge this in your own way and close this PR if you merged it.

**Comment by cloud2018** [comment]
@rubo77 
Some German translations have more letters than the English text. If the maximum width in css is too short, the translated text may may be truncated. I have not tested whether all German translations are displayed completely and not truncated.

**Comment by rubo77** [comment]
I cannot test it either. Please feel free to use it as you wish

**Comment by mamatt** [comment]
Just for the record, i have push a PR (https://github.com/ACTom/kityminder-editor/pull/6) which in addition to the french translation "enlarge" most of  the CSS fields.

**Pull request merged**
